### ISSUE TITLE
Error building on osx -> readlink: illegal option -- f 

### ISSUE THREAD

**Issue by tamarit** [parapluu/Concuerror#141]
Hi, 

I've tried to build it on OS X and the following error was raised.

```
readlink: illegal option -- f
usage: readlink [-n] [file ...]
make: stat: concuerror: Too many levels of symbolic links
```

It seems that it is a  [common problem](http://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac) in OS X. I tried  [this solution](http://stackoverflow.com/a/4031502/4162959) and it solved the problem.

I hope this helps to anyone having the same problem.

**Comment by aronisstav** [comment]
Thanks for the report! Will look at it as soon as time permits!

**Comment by aymanosman** [comment]
I also had this problem. The problem is GNU `readlink` differs from OSX `readlink`

## Workaround: Manually create symlink:
```
ln -s src/concuerror concuerror
```

The maintainers could edit the Makefile to support both versions of readlink or require OSX users to install GNU readlink via `brew install coreutils` or whatever.

**Comment by aronisstav** [comment]
Note to self for when working on this: #121 was a related issue.

**Comment by sashaafm** [comment]
Hello, I also get the same error on OS X Sierra. Using the suggested workaround didn't fix it. Are there any other possible solutions to this? Is a fix on the way?

Thanks!

**Comment by sebarys** [comment]
Hello, I am also using OS X Sierra. Receiving error like above. Any suggestions?

**Comment by aronisstav** [comment]
Yes, a fix is on its way. I will spend some time on this very soon now.

**Comment by aronisstav** [comment]
I have pushed a patch in my development branch (bf3fe22) and opened pull request #146 for this.

Since I don't have an OS machine, and [Travis can't yet handle Erlang and OS](https://github.com/travis-ci/travis-ci/issues/2320) can someone in this thread let me know if it works?

**Comment by tamarit** [comment]
Hi Stavros,

I've tried the version in you development branch and it works perfectly. 

Thanks!
