### ISSUE TITLE
Fix compilation warning by erlang/otp@7b16914

### ISSUE THREAD

**Issue by aronisstav** [parapluu/Concuerror#148]
```
src/concuerror_callback.erl:1041: erlang:get_stacktrace/0 used following
 an old-style 'catch' may stop working in a future release. (Use it inside 'try'.)
```
This is due to: https://github.com/erlang/otp/commit/7b169140b2d37f43996b9d1a94877926a471d97d

**Comment by kostis** [comment]
Fixed by https://github.com/parapluu/Concuerror/commit/d672875bf6439258b9cc0af0f60c7fecbd8bca98
