### ISSUE TITLE
Support common test suites using ct_slave 

### ISSUE THREAD

**Issue by lrascao** [parapluu/Concuerror#153]
Some interesting projects could benefit greatly from Concuerror by it support ct_slave based tests, the one i'm interested here (i'm sure there are many others) is [partisan](https://github.com/lasp-lang/partisan), a peer membership service used in the [Lasp](https://lasp-lang.readme.io/) project.

**Comment by aronisstav** [comment]
Hi @lrascao !

This issue has been on my 'wall of neglect and shame' for a while now. I believe it was motivated by a discussion after my tutorial in EUC 2017. I have lost context however, so I need help to update and review what can be done.

Is the gist here the ability to test distributed Erlang programs?

**Comment by lrascao** [comment]
Great memory, indeed it was!

> Is the gist here the ability to test distributed Erlang programs?

That's exactly the use case that we discussed during the tutorial

**Comment by aronisstav** [comment]
Given that Concuerror still has a very long way to go until it can handle any network/port related operations, I think that it is unlikely that I will try to add some easy integration with libraries such as ct_slave.

My suggestion for exploring races on distributed Erlang programs is to use a modeling library such as [klarna/vnet](https://github.com/klarna/vnet) (soon to be presented/published in the Erlang Workshop of ICFP 2018).

If there is no objection, I will close this ticket once the paper goes public (aronisstav/Concuerror#47).

**Comment by lrascao** [comment]
agreed
