### ISSUE TITLE
Black boxes in the DOT graphs

### ISSUE THREAD

**Issue by tamarit** [parapluu/Concuerror#171]
Hi Stavros & Kostis,

I'm trying to generate some graphs using the dot command provided by Graphviz. Everything goes fine, except that I've got this warning

> Warning: lime is not a known color

Graphviz does not know this color, so it decides to paint some boxes in black instead. I saw that this is a common problem, as for instance [this other issue reports](https://github.com/Ant-Grand/Grand/issues/4). The solution is easy and it just involves two lines of code: [concuerror_logger.erl:line 378](https://github.com/parapluu/Concuerror/blob/7e7ba5d282a273f21b4a6486dd6bd1dd6e20d590/src/concuerror_logger.erl#L378) and [concuerror_logger.erl:line 621](https://github.com/parapluu/Concuerror/blob/7e7ba5d282a273f21b4a6486dd6bd1dd6e20d590/src/concuerror_logger.erl#L621). Changing in both lines the word lime with limegreen should solve the problem.

Thanks and congrats for this excellent project.

**Comment by aronisstav** [comment]
Hi Tama! I just pushed a commit that fixes this! Thanks for the suggestion!

**Comment by tamarit** [comment]
Perfect!

Thank you Stavros!
