### ISSUE TITLE
code:purge not supported

### ISSUE THREAD

**Issue by massemanet** [parapluu/Concuerror#208]
tried to run concuerror on a real world application (redbug). Alas;

```
* Error: A process send a request of type '{purge,redbug_targ}' to code_server. Concuerror does not yet support this type of request to this process.
```

Perhaps there's a way to work around this?

**Comment by aronisstav** [comment]
Hi Mats!

The only "clean" way to work around this right now is to modify the version of the application used in the test so that it does not reach such code.

In the future I want to build support for mocking, so that you won't have to change the code of the application.

**Comment by kostis** [comment]
Unrelated to the main issue: The error should say `sent`, not `send`. @

**Comment by aronisstav** [comment]
@kostis Pushed fix b87f4ba

**Comment by massemanet** [comment]
I was afraid you were going to say  that...
it's fine though, I can patch easy enough.

**Comment by aronisstav** [comment]
Closing this as the behaviour is the intended one.
