### ISSUE TITLE
unsupported_process_info

### ISSUE THREAD

**Issue by massemanet** [parapluu/Concuerror#218]
unsure about this one, looks like a crash in concuerror? Or it's just giving up?
```
* Error: 
  Reason: {{unsupported_process_info,current_function},
           erlang,process_info,2,
```

**Comment by aronisstav** [comment]
This is Concuerror giving up, with a "unpolished" error message.

Viewing this report together with #217, I think that a more major problem here is that a possibly interesting crash is caught and wrapped up for debugging by OTP's own error handling code. However, OTP's code makes heavy use of debug primitives (such as `process_info(self(), current_function)` which Concuerror is not designed to support.
