### ISSUE TITLE
Add rebar3 support

### ISSUE THREAD

**Issue by aronisstav** [parapluu/Concuerror#220]
Quoting @fenollp ([here](https://github.com/parapluu/Concuerror/pull/219#issuecomment-372819658)) "rebar3 support out of the box should help with integration with other Erlang projects, maybe even Elixir projects & could turn the usage of submodules into rebar3 dependencies."

**Comment by fenollp** [comment]
Cool I'll work on this once #219 is merged!

**Comment by bieniusa** [comment]
Meanwhile, it would be great if there was at least some documentation how to get Concuerror running if the code does not consist of a single unit test (this is the only hint I found on the webpage).

So, how can I use a test that is in a /test subdirectory with the actual code being in the /src directory (and Concuerror being installed somewhere else)? I don't get whether I need to put a pointer to the module source or the beam file of the test - neither seems working for me.

**Comment by aronisstav** [comment]
Hi Annette!

If you are invoking Concuerror from the command line, you can give `--pa`,
`--pz` or `--file` options to indicate directories and/or files that should
be added in the load path and/or loaded. Can you give an example of an
invocation that doesn't behave in the expected way?

**Comment by bieniusa** [comment]
I just stumbled over http://concuerror.com/tutorials/poolboy-example which is kind of close, but there are some simplifications and omissions that I find confusing and which don't allow me to simply re-do the steps.

- Where is `poolboy_tests_1.erl` actually stored?
- You need to add `bin/concuerror` to your path (wherever you installed it.

**Comment by aronisstav** [comment]
In that tutorial, Concuerror finds the poolboy_tests_1 module via a `-f`
option whose argument is a filename, which can be absolute, relevant,
source or BEAM.

The point about having Concuerror in the path is also mentioned at the top
of the tutorial. :-)

I'll be happy to help further if you think that anything else is behaving
in surprising ways!

**Comment by bieniusa** [comment]
I think I know the problem: The unit tests I am using are actually no tests, but test_generators!

Another "surprising" thing is the following restriction:
```Error: Your test communicates with the 'application_controller' process. This is problematic, as this process is not under Concuerror's control. Try to start the test from a top-level supervisor (or even better a top level gen_server) instead.```

I hope I can find a workaround for that.

**Comment by fenollp** [comment]
Here's what I have so far https://github.com/parapluu/Concuerror/compare/master...fenollp:rebar3

**Comment by aronisstav** [comment]
Thanks for the effort @fenollp! How would you like to proceed with this? At its current state it looks like I would have to review it for squashing, rather than checking each commit.

**Comment by fenollp** [comment]
Oh yes it will be squashed. This is just to let you know how far I got and to see if you like / dislike some things, if you have ideas on why Travis is not happy, ... just general comments :)

**Comment by aronisstav** [comment]
I cannot see which Travis build fails. I will leave some comments on the overall diff as time permits.

**Comment by aronisstav** [comment]
Ah, got it: https://travis-ci.org/fenollp/Concuerror/jobs/358312439

The offending 'optimal' option can be removed. The test on that line that breaks compilation was a totally arbitrary way to remind myself to properly remove it.

**Comment by fenollp** [comment]
Thanks! Build running.

**Comment by aronisstav** [comment]
@fenollp, I cannot leave comments on a diff so when feeling you don't want to do more on this, please open a pull request here or against the master branch of my own fork (http://github.com/aronisstav/Concuerror).
