### ISSUE TITLE
Implement `make_dir` for `file_server_2`

### ISSUE THREAD

**Issue by evnu** [parapluu/Concuerror#47]
I received the following report on running Concuerror:

    Info: Instrumented io_lib
    Info: Instrumented my_SUITE
    Info: Instrumented test_server
    Info: Instrumented filename
    Info: Instrumented os
    Info: Instrumented lists
    Info: Instrumented file
    Info: Instrumented gen_server
    Info: Instrumented gen
    Error: A process send a request of type 'make_dir' to file_server_2. Concuerror does not yet support this type of request to this process.

    Please notify the developers, as this is a bug of Concuerror.

**Comment by aronisstav** [comment]
This issue is broadly similar to the one reported in #48. I am closing it and ask that we move discussion there instead.
