### ISSUE TITLE
Handling of exit_signals sent to self()

### ISSUE THREAD

**Issue by aronisstav** [parapluu/Concuerror#5]
Similar to messages sent to self(), these should be delivered immediately and race correctly with everything else.

**Comment by aronisstav** [comment]
Comment from @rvirding: http://erlang.org/pipermail/erlang-bugs/2012-December/003221.html

This is still not fixed in OTP `source-269dae4`.

**Comment by rvirding** [comment]
Yes, I know. But I had honestly not expected them to change it. :-) :-(

Robert
