### ISSUE TITLE
Integration into erlang.mk

### ISSUE THREAD

**Issue by essen** [parapluu/Concuerror#50]
Hello!

I was very impressed with Concuerror at the SF tutorial last year and would like to integrate Concuerror with my daily development. Part of that involves adding it to erlang.mk and part of that making it work with other tools like Common Test (only looking at a single-node usage at this point) or Triq.

It seems to be well integrated with Eunit (considering it requires an entry function of 0 arity called 'test' by default) so I tried that first. Here's the output I got (Erlang 17.4):

``` erlang
 ~/tmp/Concuerror/concuerror -m cowboy_router
Concuerror started at 09 May 2015 14:12:06
Writing results in concuerror_report.txt

Info: Instrumented io_lib
Info: Instrumented cowboy_router
Info: Instrumented eunit
Info: Instrumented proplists
Info: Instrumented eunit_tty
Info: Instrumented eunit_listener
Info: Instrumented erlang
Info: Instrumented eunit_serial
Info: Instrumented sets
Info: Instrumented lists
Info: Instrumented eunit_lib
Info: Instrumented gb_trees
Info: Instrumented dict
Info: Instrumented eunit_server
Info: Instrumented queue
Info: Instrumented eunit_proc
Error: Concuerror does not currently support calls to built-in erlang:statistics/1 (found in eunit_proc.erl line 320). Please notify the developers.
```

For Common Test, I'm not even sure where to begin. The way things are right now it seems that I would have to generate some kind of module to have a test/0 function that then calls ct:run. Could work, but perhaps there could be a way to have Concuerror accept an MFA instead of just MF? This way I could just give everything from the command line. I believe that should work for Triq too.

**Comment by aronisstav** [comment]
Hi Loïc! Thanks for trying out Concuerror!

The error that you are getting is something that @kostis and I have also noticed, but we have not decided on a fix yet.

The problem when invoking Concuerror with the `test/0` function generated by EUnit is that the entire scaffolding of EUnit is run under Concuerror. This includes the mentioned call to `erlang:statistics/1` which cannot be handled in systematic testing in a sane way.

We therefore need a way to 'reverse the order' of the tools: Concuerror should be the one to run under EUnit and not the other way round. For that we need to document the Erlang frontend of the tool (and allow for multiple test runs to be possible under the same 'session') and possibly add e.g. a parse transform that can directly turn EUnit tests into calls to Concuerror. That should also work for Common Test.

I would very much like to hear your thoughts about this.

**Comment by essen** [comment]
OK that's a tough one.

I'm not sure where you would hook Concuerror to be honest. For example Common Test creates a new process every time it calls a callback, so the process that initializes the system (for example, bringing Cowboy up with a test configuration) is not the same as the process that tests it (doing requests against the system previously set up).

I think it could still be interesting to plug into just the system itself but the system can be initialized differently depending on the test suite (init_per_suite, init_per_group...) so I doubt you can truly automate it with a parse transform.

There's also the issue of running tests in parallel.

On the other hand, you're right, I believe the first step is to document the Erlang frontend. At the very least we will be able to experiment and figure things out, and if necessary perhaps patch other tools to allow plugging Concuerror exactly where it should be plugged.

**Comment by aronisstav** [comment]
Just writing down some more thoughts on this...

Command line options (a list of whom is available with 'concuerror -h') can be given as a `proplist` to `concuerror:run/1` (the keys are just the atoms shown). I am not sure I will find the time to provide something more detailed there.

A reasonable approach to combine EUnit-like tests with Concuerror would be to have a header file that would convert tests to calls to Concuerror. However that may not be that simple:

* A major catch is that due to code instrumentation (and a lack of a properly isolated central server that could keep track of instrumented code) running Concuerror twice on the same VM would not work, so e.g. slave nodes would be needed to do the actual testing.
* Concuerror does not like not being in control of everything, so any communication with processes spawned outside the test will lead to complaints. Setting up a system outside Concuerror, for example, while being a very reasonable use case, is not something that is currently supported (neither is limiting a test to the part after some initial setup is completed, although this is a lot easier to add).

**Comment by essen** [comment]
I will experiment writing a lightweight common_test/eunit runner to run concuerror on top of it after EUC.

One note though: it would be good if you had a DEPS_DIR ?= deps variable in the Makefile, this way you will download getopt in the right folder for erlang.mk. I will send a patch later on, just putting it here to remember.

**Comment by aronisstav** [comment]
After the merge of #88, it should be now possible to call Concuerror multiple times in the same instance of the VM.

**Comment by essen** [comment]
Thanks, I will see if I can make up time soon.

**Comment by essen** [comment]
I'm trying to set this up in a Common Test suite in Ranch. I am running into a few minor issues (leaving them aside for now) and one major issue.

I get the following:

```
Error: A process tried to send a message to system process ranch_sup. Concuerror does not currently support communication with this process. Please contact the developers for more information.
```

Depending on what I comment out, the event trace grows bigger or smaller. I believe the problem occurs at the call to `supervisor:start_child`.

My CT test case is simple:

```
start_stop(_) →
    _ = code:ensure_loaded(ranch_tcp),
    ok = concuerror:run([
        {module, ?MODULE},
        {test, do_start_stop},
        {keep_going, true}
    ]).

do_start_stop() →
    ranch_sup:start_link(),
    Ref = start_stop,
    {ok, _} = ranch:start_listener(Ref, 1,
        ranch_tcp, [],
        echo_protocol, []),
    ok = ranch:stop_listener(Ref).
```

The call to `concuerror:run` returns `fail`.

Any suggestion?

**Comment by aronisstav** [comment]
It seems that the supervisor `ranch_sup` is already running before the test, causing Concuerrror to complain about communication with a process outside its control.

I cannot get this error message when running your test via the script or directly through an Erlang shell.

**Comment by essen** [comment]
Ah thanks for the tip, it is indeed already started. Now to find why...

**Comment by aronisstav** [comment]
A while ago I wrote a tutorial about running Concuerror with EUnit:

http://parapluu.github.io/Concuerror/tutorials/concuerror-eunit

I believe that a similar approach can be used for Common Test.

Should I consider this issue closed for the time being?

**Comment by essen** [comment]
Yeah no worries, let me close it. Thanks!
