### ISSUE TITLE
replaying a built-in returned a different result than expected

### ISSUE THREAD

**Issue by Cloven** [parapluu/Concuerror#70]
it's highly likely that I'm not yet using concuerror correctly.  

Nevertheless, using concuerror commit 1c3ef97d02cbcecda1702601d5c44482252ce048:

$ ../Concuerror/concuerror --pa ebin deps/*/ebin -m paros --non_racing_system user  --treat_as_normal shutdown

[...short time passes...]

Error: On step 323, replaying a built-in returned a different result than expected:
  original:
    {event,<0.117.0>,
       {exit_event,<0.117.0>,
                   [<0.124.0>,<0.131.0>,<0.134.0>],
                   [{#Ref<0.0.1.1640>,<0.72.0>,<0.117.0>}],
                   mary,shutdown,[],running,false},
       #Ref<0.0.1.1674>,exit,[]}
  new:
    {event,<0.117.0>,
       {exit_event,<0.117.0>,
                   [<0.124.0>,<0.131.0>,<0.134.0>],
                   [{#Ref<0.0.1.1640>,<0.72.0>,<0.117.0>}],
                   mary,shutdown,[],waiting,false},
       #Ref<0.0.1.1674>,exit,[]}

Please notify the developers, as this is a bug of Concuerror.

Done! (Exit status: error)
  Summary: 1 errors, 98/567 interleavings explored

This result is repeatable every time I run it.  I can provide github access to the project, files, debugging time, etc.; whatever's needed.

**Comment by kostis** [comment]
Thanks for reporting this issue, but in order to reproduce it and investigate what's happening we would like access to the 'paros' module (and its dependencies) somehow.

**Comment by Cloven** [comment]
Certainly.  What github account would you like me to add as a contributor to the paros module?

**Comment by kostis** [comment]
@aronisstav and @kostis

**Comment by Cloven** [comment]
done.

**Comment by aronisstav** [comment]
@Cloven Thanks! I can replicate the error. I will get back to you soon.

**Comment by aronisstav** [comment]
@Cloven I have written a patch (aronisstav@c0d3b20). It fixes the crash and one more small issue I noticed while running your command line. It will be merged eventually, but feel free to check out the branch and use it for the time being.

**Comment by aronisstav** [comment]
I have merged the fix into `master`. I am therefore closing this issue.

I accidentally removed the 'fixes #70' from the description from the relevant commit (which is now 52bce59229a76f9179748350808ff74231a09cbd).
