### ISSUE TITLE
replaying a built-in returned a different result than expected - part 3

### ISSUE THREAD

**Issue by Cloven** [parapluu/Concuerror#75]
Even if my code implementation never works, I'm apparently excellent at generating canonical test cases for Concuerror, which I will now add to my resume as a significant accomplishment. :)

Following instructions from the previous issue, I added --instant_delivery (which seems to significantly speed up the interleaves checked per second as well, which is good).  I then saw a number of failures owing to sleep set blockage.  I'm still trying to understand sleep set blockage, but in the meantime I decided to add the --optimal true flag, thinking it would enabled optimal DPOR per the paper, which in turn appeared to me (from a non-expert reading) to suggest that it would eliminate sleep set blocks.  Nevertheless, I still got a fair number of sleep set blocked errors.  And, after a long while, I get another replaying-a-built-in issue.

The branch of paros in question this time is 'concuerror_issue3'.  As before, you have access to the repo.
```
../Concuerror/concuerror --pa ebin --pa deps/goldrush/ebin --pa deps/lager/ebin --pa deps/triq/ebin -m paros --treat_as_normal shutdown -a 1000  --instant_delivery -k --optimal true
Concuerror started at 30 Nov 2015 21:58:05
Writing results in concuerror_report.txt

Info: Instrumented io_lib
Info: Instrumented paros
Info: Instrumented paros_sup
Info: Instrumented supervisor
Info: Instrumented gen_server
Info: Instrumented gen
Info: Instrumented proc_lib
Info: Instrumented erlang
Info: Instrumented lists
Info: Instrumented paros_replica
Info: Instrumented paros_kv
Info: Instrumented paros_deps
Info: Instrumented proplists
Info: Instrumented error_logger
Info: Instrumented gen_event
Tip: An abnormal exit signal was sent to a process. This is probably the worst thing that can happen race-wise, as any other side-effecting operation races with the arrival of the signal. If the test produces too many interleavings consider refactoring your code.
Info: Instrumented gen_fsm
Warning: Some abnormal exit reasons were treated as normal (--treat_as_normal).
Info: Instrumented paros_instance
Info: You can see pairs of racing instructions (in the report and --graph) with '--show_races true'
Warning: Some interleavings were 'sleep-set blocked'. This is expected if you have specified '--optimal false', but reveals wasted effort.
Warning: Continuing after error
Error: On step 247, replaying a built-in returned a different result than expected:
  original:
    {event,<0.126.0>,
    {receive_event,
        {message,
            {'$gen_cast',{commit,{0,{set,x,1},2,[{julian,1}],{bruce,1}}}},
            #Ref<0.0.262145.1933>,0},
        #Fun<gen_server.0.77557606>,<0.126.0>,infinity,false},
    #Ref<0.0.262145.191229>,
    [382,{file,"gen_server.erl"}],
    [{message_received,#Ref<0.0.262145.1933>}]}
  new:
    {event,<0.126.0>,
    {receive_event,
        {message,
            {'$gen_cast',{commit,{0,{set,x,1},2,[{julian,1}],{bruce,1}}}},
            #Ref<0.0.262145.30792>,0},
        #Fun<gen_server.0.77557606>,<0.126.0>,infinity,false},
    #Ref<0.0.262145.191229>,
    [382,{file,"gen_server.erl"}],
    [{message_received,#Ref<0.0.262145.30792>}]}

Please notify the developers, as this is a bug of Concuerror.

Done! (Exit status: error)
  Summary: 1 errors, 15845/16023 interleavings explored (29 sleep-set blocked)
```

**Comment by Cloven** [comment]
As a possible hint here (and I don't know for sure), this code is iterating through a map and gen_casting to certain of its members.  Since concuerror was originally written pre-maps, it's possible that it is confused by the behavior of maps.  Or, I could be barking up the wrong tree.

**Comment by aronisstav** [comment]
Hi Felix! Thank you for the report! I can give you a reference letter if one ever doubts your Concuerror tester skills! :-) Some more comments:
- 'optimal' is enabled by default, and should indeed eliminate sleep-set blocking. This is a very good find!
- Maps should not be a problem, as their operations are never involved in races (they are always on local data structures).

I have reproduced the reported behaviour. The 1st sleep set blocked interleaving occurs at ~3600 interleavings and there is indeed a crash after 15845.

**Comment by aronisstav** [comment]
So the patch mentioned above (currently cooking on Travis) takes care of the sleep set blocking at least. Unfortunately it still crashes after 19426 interleavings with the 'usual reason'. I will leave this issue open and I will check it again when I have a patch for #74.

**Comment by aronisstav** [comment]
@Cloven: This is ready for one more round of testing. After the merge of #84 , I have been running this test for a while with 52991 explored (and counting) and no problems.

**Comment by Cloven** [comment]
believe this may be fixed.  Will open up a new issue if I encounter more replay issues.
